version: "3"

services:
  nextjs:
    build: .
    restart: unless-stopped
  nginx:
    image: jonasal/nginx-certbot:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    environment:
      - CERTBOT_EMAIL=tamzhermin@gmail.com
    volumes:
      - ./nginx:/etc/nginx/user_conf.d
      - nginx_secrets:/etc/letsencrypt

volumes:
  nginx_secrets:
