name: Daily Email API

on:
  schedule:
    - cron: "0 9 * * *" # 5PM SGT
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        run: |
          curl --request GET \
          --url 'https://leetnode.vercel.app/api/email/sendEmail' \
          --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'
