name: Daily Email API

on:
  push:
    branches: [settings]
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Call API
        run: |
          curl --request GET \
          --url https://leetnode-git-dev-zhermin.vercel.app/api/email/sendEmail \
          --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'
